### ISSUE TITLE
Error message in from autonode task

### ISSUE THREAD

**Issue by jimmytidey** [jimmytidey/obs#54]
line":"63","file":"synced-cron-server.js","message":"SyncedCron: Exception \"Check Tasks\" TypeError: Cannot call method 'toLowerCase' of null\n    at are_nodes_equal (app/server/tasks/2_auto_node.js:24:18)\n    at app/server/tasks/2_auto_node.js:34:10\n    at packages/underscore/underscore.js:184:1\n    at Array.some (native)\n    at _.some._.any (packages/underscore/underscore.js:233:1)\n    at Function._.find._.detect (packages/underscore/underscore.js:183:1)\n    at node_match (app/server/tasks/2_auto_node.js:33:13)\n    at app/server/tasks/2_auto_node.js:45:4\n    at Array.reduce (native)\n    at Function._.reduce._.foldl._.inject (packages/underscore/underscore.js:139:1)","time":{"$date":1437600771007},"level":"info"}

**Comment by jimmytidey** [comment]
problem with dealing with null values
